export const DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID!;
export const TRANSACTION_ID = process.env.NEXT_PUBLIC_APPWRITE_TRANSACTION_ID!;
export const PROJECT_ID = process.env.NEXT_PUBLIC_APPWRITE_PROJECT_ID!;
export const PROFILE_ID = process.env.NEXT_PUBLIC_APPWRITE_PROFILE_ID!;
export const INVESTMENT_ID = process.env.NEXT_PUBLIC_APPWRITE_INVESTMENT_ID!;
export const OWNER_ID = process.env.NEXT_PUBLIC_OWNER_ID!;
